server:
  port: 7777

spring:
  datasource:
    #  h2 database unique name
    #    generate-unique-name: false
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

